  - alias: "Media player paused/stopped"
    trigger:
      - platform: state
        entity_id: media_player.rasplecs
        from: 'playing'
#    condition:
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
    action:
        service: scene.turn_on
        entity_id: scene.salon_normal

  - alias: "Media player playing"
    trigger:
      - platform: state
        entity_id: media_player.rasplecs
        to: 'playing'
#    condition:
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
    action:
        service: scene.turn_on
        entity_id: scene.salon_dim


  - alias: Update notifications
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.telegrambot
      data:
        message: 'There is a new Home Assistant release available.'
